USE BONUS_TRACK;
-- > 1
SELECT ARTISTA, TITULO, GENERO FROM TOP_SPOTIFY ORDER BY ARTISTA, TITULO LIMIT 10;
-- > 2
SELECT ARTISTA, TITULO, GENERO FROM TOP_SPOTIFY ORDER BY ARTISTA, TITULO LIMIT 5 OFFSET 10;
-- > 3
SELECT * FROM TOP_SPOTIFY WHERE ARTISTA = 'MADONNA';
-- > 4 
SELECT * FROM TOP_SPOTIFY WHERE GENERO = 'POP' ORDER BY TITULO;
-- > 5
SELECT * FROM TOP_SPOTIFY 
WHERE GENERO = 'Pop' AND ANO = 2015 
ORDER BY ARTISTA, TITULO ;
-- > 6
SELECT * FROM TOP_SPOTIFY WHERE ANO < 2011 AND GENERO = 'Dance Pop' ORDER BY ARTISTA, TITULO;